### ISSUE TITLE
Fixes: Consternation on the Constellation

### ISSUE THREAD

**Issue by alandwarinasia** [Chr1Z93/loadable-objects#25]
the current version of the Consternation on the Constellation standalone custom scenario has a few issues:

- no metadata (no clue spawning, auto connections, victory highlight, etc)
- incomplete tags (story assets dont snap)
- the bridge and deck lounge/theater locations seem to be transposed on the map

i'm not sure who 'authored' the current implementation, but i've taken the liberty of fixing those issues

[myriad-constellation_on_the_consternation-remastered.zip](https://github.com/Chr1Z93/loadable-objects/files/12708422/myriad-constellation_on_the_consternation-remastered.zip)

**Comment by Chr1Z93** [comment]
Did some final touches and updated it! Thanks for the work <3
