### ISSUE TITLE
exhaledinnards projects

### ISSUE THREAD

**Issue by exhaledanxiety** [Chr1Z93/loadable-objects#7]
bloodborne & night of vespers have both been recently updated
TYSM in advance

https://steamcommunity.com/sharedfiles/filedetails/?id=2918733264
https://steamcommunity.com/sharedfiles/filedetails/?id=2959774501

**Comment by Chr1Z93** [comment]
Thanks for the notification! Both added to download menu and the next update will contain a placeholder box in the fan-made campaigns for Bloodborne.
