### ISSUE TITLE
flanfys projects

### ISSUE THREAD

**Issue by flanfy** [Chr1Z93/loadable-objects#8]
Updated Magical Girl Arkham Project recently, created Girl's Frontline Investigators, original investigators, Tanya.
Removed tag based bags from MGAP.
MGAP
https://steamcommunity.com/sharedfiles/filedetails/?id=2847184689
GF
https://steamcommunity.com/sharedfiles/filedetails/?id=2947124523
OC
https://steamcommunity.com/sharedfiles/filedetails/?id=2912116593
Tanya
https://steamcommunity.com/sharedfiles/filedetails/?id=2949995900

**Comment by Chr1Z93** [comment]
Updated MGAP and added the others to the download menu
