### ISSUE TITLE
[Custom] The Ghosts of Onigawa: Investigator Expansion Update (v1.3)

### ISSUE THREAD

**Issue by alandwarinasia** [Chr1Z93/loadable-objects#9]
Recently updated [The Ghosts of Onigawa](https://github.com/ArkhamDotCards/theghostsofonigawa)'s investigator expansion box to be compliant with the SCE3.0+ metadata standards. This should be the final update to the investigator expansion. (I'll make a seperate issue for the updated campaign box when its ready)

Steam workshop link if you want to grab the object yourself: https://steamcommunity.com/sharedfiles/filedetails/?id=2544629522

Or here's the json object for the investigator box (had to zip it for some godforsaken reason):
[adctheghostsofonigawainvestigatorv13.zip](https://github.com/Chr1Z93/loadable-objects/files/11279891/adctheghostsofonigawainvestigatorv13.zip)

Cheers,
-H

**Comment by Chr1Z93** [comment]
Updated
